### PR TITLE
Eliminate laser_mode config item.  Use Laser spindle instead

### PR DESCRIPTION
**Pull request by MitchBradley**
$32 is supported, but setting it does not do anything.

### CODE REVIEW

**Comment by bdring** [comment]
Should we move `disable_laser_during_hold:` to laser? .. or get rid of it?
`direction_pin:` ??

The spin delays go away with my branch

```yaml
software_debounce_ms: 0
arc_tolerance: 0.002
junction_deviation: 0.010
verbose_errors: false
report_inches: false
homing_init_lock: false
enable_parking_override_control: false
deactivate_parking_upon_init: false
check_limits_at_init: false
limits_two_switches_on_axis: false
disable_laser_during_hold: true
use_line_numbers: false
Laser:
  pwm_freq: 5000
  output_pin: gpio.14
  enable_pin: gpio.12
  direction_pin: NO_PIN
  disable_with_zero_speed: false
  zero_speed_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool: 100
  speeds: 0=0.000% 255=100.000%
  ```

**Comment by MitchBradley** [comment]
disable_laser_during_hold seems redundant.  I have eliminated it.

**Comment by MitchBradley** [comment]
direction_pin is inherited from PWM spindle.  To make it go away for laser, we would have to change the inheritance hierarchy.

**Comment by atlaste** [comment]
@MitchBradley One way to do it is not to use the base classes of 'group', except for what's needed. 

```
    class Laser { ...
        void group(Configuration::HandlerBase& handler) override {
            handler.item("pwm_freq", _pwm_freq);
            handler.item("output_pin", _output_pin);
            handler.item("enable_pin", _enable_pin);
            handler.item("disable_with_zero_speed", _disable_with_zero_speed);
            handler.item("zero_speed_with_disable", _zero_speed_with_disable);

            Spindle::group(handler);
        }
    }
```

Unfortunately, that's bad for maintenance; if items are added to base classes, Laser won't get them. So what developers usually do in such a scenario is make a protected (non-virtual) member function in PWM / OnOff spindle that implements group with a boolean flag. So:

    class Laser { ...
        void group(Configuration::HandlerBase& handler) override {
            PWMSpindle::groupDetails(handler, false);
        }
    }
    class PWMSpindle { ...
    protected:
        void groupDetails(Configuration::HandlerBase& handler, bool hasDisable) override {
            handler.item("pwm_freq", _pwm_freq);
            OnOffSpindle::groupDetails(handler, false);
        }
    public:
        void group(Configuration::HandlerBase& handler) override {
            PWMSpindle::groupDetails(handler, true);
        }
    }
    class OnOffSpindle { ...
    protected:
        void groupDetails(Configuration::HandlerBase& handler, bool hasDisable) {
            if (hasDisable) {
                 handler.item("disable_pin", _disable_pin);
            }

            handler.item("output_pin", _output_pin);
            handler.item("enable_pin", _enable_pin);
            handler.item("disable_with_zero_speed", _disable_with_zero_speed);
            handler.item("zero_speed_with_disable", _zero_speed_with_disable);

            Spindle::group(handler);
        }
    public:
        void group(Configuration::HandlerBase& handler) override {
            OnOffSpindle::groupDetails(handler, true);
        }
```

**Comment by bdring** [comment]
@MitchBradley  Thanks, I cleaned up the data folder too.

**Pull request merged**
